# -*- coding: utf-8 -*-
"""ch1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NVX628YCNwc-pv3DTbOc7HWcF_Z5K4_B
"""

#print("學習","Python")
#print("learning","Python",sep="\t")
#print("learning","Python",sep="\n")


name=input("請問貴姓?")
print("你好", name)
age=input("請問年紀?")           #課本為int(input("請問年紀?"))，但這樣就只能輸入數字而不能為文字
print("今年",age, "歲")
weight=input("請問體重?")          #課本為float(input("請問年紀?"))，但這樣就只能輸入數字而不能為文字
print("體重是", weight, "公斤")