# -*- coding: utf-8 -*-
"""ch2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1seI7Fz4sMqbaivObOi4R66woa-J4RwSY
"""

#print(int("100",2))      #二進位
#print(int("1",2))
#print(float("3"))        #將數字都加上小數點第一位

#str()       #將輸入的物件轉成字串

#不同types:
#b=True
#print(b, type(b))
#num=20
#print(num,type(num))
#pi=3.14
#print(pi,type(pi))
#s="Hello"
#print(s,type(s))

#id為物件編號
#a=1
#print(a, id(a))
#a="python"
#print(a, id(a))

#if 5==2 ==True:
#  print("True")
#else:
#  print("False")

#A=(5<2)
#print(A) #判斷A的真假值(不用"")

#in 是否包含
#not in 是否不包含
#is 是否為相同物件(包含變數左右兩邊都要相同)
#not is 是否不為相同物件

#s="123456789"
#print("s=", s, "s[-1::-1]=", s[-1::-1])          #第N個和倒數第N個反轉

#\t tab為8個半形字元

#String="春眠不覺曉，處處聞啼鳥，夜來風雨聲，花落知多少。"
#List=String.split(",")
#print(List)



#習題:
#exam1=int(input("請輸入第一次期中考成績?"))
#exam2=int(input("請輸入第二次期中考成績?"))
#final=int(input("請輸入期末考成績?"))
#print("總分=",exam1+exam2+final, "平均=", (exam1+exam2+final)/3)

#foot=int(input("請輸入?尺"))
#inch=int(input("請輸入?吋"))
#print((foot*12+inch)*2.54, "公分")

#座號=int(input("請輸入座號?"))
#組別=(座號-1)//5+1                   #-1因為從1號開始分組;+1因為從第一組開始編組
#print("組別是"，組別)

#罐數=int(input("請輸入購買罐數"))
#金額=(罐數//12)*200+(罐數%12)*20
#print("總共",金額,"元")

s=input("請輸入一行英文句子")
words=s.split()
print(words)
s1=" ".join(words)
print(s1)
s2=s.title()
print(s2)