# -*- coding: utf-8 -*-
"""ch4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZqiTYss7jALvhggM_vE2rZPnga2A8g3j
"""

#a=int(input("請輸入三角形邊長a長度為?"))
#b=int(input("請輸入三角形邊長b長度為?"))
#c=int(input("請輸入三角形邊長c長度為?"))
#if (a<b+c) and (b<a+c) and (c<a+b):   #一定要有括號，否則error
#  print("可構成三角形")
#else:
#  print("無法構成三角形")

#eye=float(input("請輸入眼睛度數?"))
#if eye<=0.9:
#  print("近視")
#else:
#  print("視力正常")

#X=float(input("請輸入X軸座標?"))
#Y=float(input("請輸入Y軸座標?"))
#if (X>0) and (Y>0):   #或(X>0 and Y>0)
#  print("第一象限")
#elif (X<0) and (Y>0):
#  print("第二象限")
#elif (X<0) and (Y<0):
#  print("第三象限")
#elif (X>0) and (Y<0):
#  print("第四象限")
#else:
#  print("該座標在座標軸上")

#temp=float(input("請輸入體溫?"))
#if temp<36:
#  print("體溫過低")
#elif 36<temp<38:
#  print("體溫正常")
#elif 38<temp<39:
#  print("體溫有點燒")
#else:
#  print("高燒")

#year=int(input("請輸入年份?"))
#if year%400==0:        #或((year%400)==0)
#  print(year,"是閏年")
#elif year%100==0:
#  print(year,"非閏年")
#elif year%4==0:
#  print(year,"是閏年")
#else:
#  print(year,"非閏年")