# -*- coding: utf-8 -*-
"""ch5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19J4b5O5ISMmIFpoG77yMYsmV6S4XR2T5
"""

#range(起始值,終止值,遞增(減)值)  #預設起始值0，遞增值1，數字串列會到終止值前一數字
#for i in range(100,90,-3):
#  print(i)

#for語法:(用於已知重複次數的程式)
#for 迴圈變數 in range(起始值,終止值,遞增(減)值):
#  重複的程式

#迴圈中可跳出迴圈(break)，跳過正在執行的迴圈執行迴圈的下一輪(continue)
#迴圈最後有些會加else，表示迴圈若正常結束，不是遇到break，就會執行else

#s=int(input("請輸入加總起始值?"))
#e=int(input("請輸入加總終止值?"))
#inc=int(input("請輸入加總遞增值?"))
#sum=0
#for i in range(s,e,inc):            #i表各次加總起始值
#  sum=sum+i
#  print("i為",i,"加總結果為",sum)

#上述可簡化用sum
#s=int(input("請輸入加總起始值?"))
#e=int(input("請輸入加總終止值?"))
#inc=int(input("請輸入加總遞增值?"))
#print(sum(range(s,e,inc)))         #直接得到最後結果

#while語法:(用於不固定次數的迴圈，依測試條件成立與否決定是否跳出迴圈)
#迴圈變數=初始值
#while 迴圈變數<終止值:
#  重複的程式
#  迴圈變數=迴圈變數+遞增(減)值

#例如上述改成while迴圈:
#i=3
#while i<13:
#  sum=sum+i
#  i=i+3

#M=int(input("請輸入M?"))
#fac=1              #初始化階乘fac=1
#i=1
#while(fac<M):           #fac為i的階乘
#  i=i+1
#  fac=fac*i
#print(i,"階乘為",fac,">",M)

#random內建模組的函式可隨機產生介於特定a,b間的整數
#import random
#target=random.randint(a,b)

#import random
#target=random.randint(1,100)
#guess=0
#while target !=guess:                #當target和guess不同時繼續跑迴圈
#  guess=int(input("請輸入1到100的數字"))
#  if target<guess:
#    print("猜小一點")
#  elif target>guess:
#    print("猜大一點")
#  else:
#    print("猜中了!")

#prime旗標變數:代表程式的執行狀態

#num=int(input("請輸入一個整數"))
#j=2
#prime=True
#while j<num:
#  if(num%j==0):
#    prime=False    #設旗標，若為非質數/因數則false
#    break
#  j+=1          #或j=j+1
#  if prime:
#    print(num,"是質數")
#  else:
#    print(num,"不是質數")

#巢狀迴圈
#for i in range(1,10):
#  for j in range(1,10):
#    print(i,"*",j,"=",i*j,"\t",sep="",end="")
#  print()

#import math
#for i in range(2,1000):
#  j=2
#  prime=True
#  while j <= math.sqrt(i):
#    if (i%j==0):
#      prime=False
#      break
#    j+=1
#    if prime:
#      print(i,"是質數")

#while True:               #while True:無窮迴圈，表示永遠測試條件都成立
#  account=input("請輸入帳號")
#  password=input("請輸入密碼")
#  if (account=="abc" and password=="123"):
#    print("帳號密碼正確")
#    break
#  else:
#    print("登入失敗")

#t=tuple("America")
#for i in t:          #讀取t中每個元素，i為元素
#  print(i)
#for i in range(0,len(t)):   #讀取t中每個元素，i為位置的數字
#  print(i,t[i])

#List=["milk","egg","coffee bean"]
#for i in List:
#  print(i)
#for i in range(0,len(List)):
#  print(i, List[i])
#for i, name in enumerate(List, start=1):  #enumerate從指定start開始編號，編號指定給i，元素指定給name
#  print(i, name)

#生成式(comprehension)vs.產生器(generator)
#串列生成式:[運算式 for 元素 in 可迭代的物件]
  #ex. [x for x in range (1,6)]
  #等於
  #a=[]
  #for i in range(1,6):
  #  a.append(i)
#也可加上條件:[運算式 for 元素 in 可迭代的物件 if 條件判斷]
#甚至巢狀:[運算式 for 元素1 in 可迭代的物件1 for 元素2 in 可迭代的物件2]      #ex. [(i.j.i*j) for i in range(1,10) for j in range(1,10)]
#字典生成式:{鍵:值 for 元素 in 可迭代的物件}
#集合生成式:{運算式 for 元素 in 可迭代的物件}

#但!沒有tuple生成式，可用產生器:(運算式 for 元素 in 可迭代的物件)，限執行一次


#num=int(input("請輸入求前幾項費氏數列?"))
#a=1
#b=1
#print(1,a)    #若少這一行就少了第一項/第二項
#for i in range(2, num+1):  #+1因為第一項需計算
#  a,b=b,a+b
#  print(i,a)


#將進酒（唐·李白）
#詩="君不見，黃河之水天上來，奔流到海不復回。君不見，高堂明鏡悲白髮，朝如青絲暮成雪。人生得意須盡歡，莫使金樽空對月。天生我材必有用，千金散盡還復來。烹羊宰牛且爲樂，會須一飲三百杯。岑夫子，丹丘生，將進酒，君莫停。與君歌一曲，請君爲我側耳聽。鐘鼓饌玉不足貴，但願長醉不復醒。古來聖賢皆寂寞，惟有飲者留其名。陳王昔時宴平樂，斗酒十千恣歡謔。主人何爲言少錢，徑須沽取對君酌。五花馬，千金裘，呼兒將出換美酒，與爾同銷萬古愁。"
#Dic={word:詩.count(word) for word in set(詩) if word != "。" and word != "，" and 詩.count(word)>2}
#print(Dic)
#Dict={word:詩.count(word) for word in set(詩) if word != "。" and word != "，" and 詩.count(word)==3}      #或dic2={k;v for k,v in Dic.items() if v==3}
#print(Dict)

#sec1={chr(ord("a")+i):chr(ord("a")+i-1) for i in range(26) if i%2}
#sec2={chr(ord("a")+i):chr(ord("a")+i+1) for i in range(26) if i%2==0}
#sec1.update(sec2)
#print(sec1)
#s="how are you"
#print(s)
#ss=" "
#for j in s:
#  if j != " ":
#    ss += sec1[j]
#  else:
#    ss += " "
#print(ss)


#n=int(input("請輸入正整數n?"))
#sum=0
#for i in range(1,n+1):
#  sum=sum+i*i
#print(sum)
#或
#i=1   #因為要是正整數，起始值為1
#sum=0
#while i <n+1:
#  sum=sum+i*i
#  i=i+1
#print(sum)


#List=[x for x in range(1,1000) if (x%2 !=0) and (x%3 !=0)]
#print(List)
#或
#for i in range(1,1000):
#  if ((i%2 !=0) and (i%3 !=0)):
#    print(i)


#sum=0
#i=0     #似乎i=0或i=1結果都相同
#while sum<1000:
#  i=i+1
#  sum=sum+i*i
#print(i)


#for i in range(1,20):
#  for j in range(1,20):
#    print(i*j)
#  print()

#for i in range(1,1001):
#  sum=0
#  for j in range(1,i):
#    if (i%j==0):
#      sum += j
#  if sum==i:
#    print(i, "為完全數")


import random
while True:
  dice=random.randint(1,6)
  print(dice)
  if dice==6:
    break