# -*- coding: utf-8 -*-
"""ch6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GzxbLSnvMtY3rC15mPv0yihx6bGbR84l
"""

#def BMI(h,w):
#  BMI = w/(h*h)
#  print ("BMI=", BMI)
#  if BMI<18:
#    print("體重過輕")
#  elif BMI<24:
#    print("體重正常")
#  elif BMI<27:
#    print("體重過重")
#  else:
#    print("體重肥胖")
#h=float(input("請輸入身高(m)?"))
#w=float(input("請輸入體重(kg)?"))
#BMI(h,w)

#或
#def BMI(w,h):
#  return w/(h*h)
#w=float(input("請輸入體重(kg)?"))
#h=float(input("請輸入身高(m)?"))
#bmi=BMI(w,h)
#print("BMI為", bmi)
#if(bmi<18):
#  print("體重過輕")
#elif(bmi<24):
#  print("體重正常")
#elif bmi<27:
#  print("體重過重")
#else:
#  print("體重肥胖")


#import math
#def prime(num):
#  j=2
#  prime=True
#  while j<= math.sqrt(num):   #用開根號找質數
#    if (num%j==0):
#      return False
#    j+=1
#  return True
#for i in range(2,101):
#  if prime(i):
#    print(i, "是質數")

#或
#def prime(num):
#  j=2
#  prime=True
#  while j<num:
#    if(num%j==0):      #用因數找質數
#      prime=False
#      break
#    j+=1
#  if prime:
#    return num
#  else:
#    pass
#for i in range(2,101):
#  if prime(i):
#    print(i,"是質數")


#呼叫函式時，所帶入的輸入值會取代原函式對應位置的值


#from datetime import datetime
#def ymd():
#  now=datetime.now()
#  return=(now.year, now.month, now.day)
#y,m,d=ymd()          #tuple開箱(tuple uppacking)
#print(y,m,d)


#help(min):讀取函式的說明文件
#print(min._doc_):印出函式的說明文件

#用函式製作產生器，可以產生一個序列的資料。產生器要用yield回傳，其會記錄上一次回傳時函式的狀態，不會從頭到尾都執行。(?)


#def fac(num):
#  if num ==1:
#    return 1
#  else:
#    return num*fac(num-1)
#n=int(input("請輸入n值?"))
#ans=fac(n)
#print(n,"!=",ans,sep="")


#def 最大公因數(m,n):
#  if m==0:
#    return n
#  else:
#    print(m,"和",n,"的最大公因數=",n%m, "和", m,"的最大公因數", sep="")
#    return 最大公因數(n%m, m)
#m=int(input("請輸入m值?"))
#n=int(input("請輸入n值?"))
#ans=最大公因數(m,n)
#print(m,"和",n,"的最大公因數為",ans,sep="")